Fix session start time
Dynatrace/openkit-dotnet pull request #43
Opened 2018-07-23 12:53 UTC by stefaneberl

When reporting a session start event, `t0` must be set to `0` according to the protocol.

2018-07-23 15:16 UTC, y0chanan requested changes

2018-07-23 15:16 UTC, y0chanan commented on src/openkit-shared/Protocol/HTTPClientHttpClient.cs
> +    {
as discussed before, the cascaded #if preprocessor declarations are hard to read.

2018-07-24 12:36 UTC, thomasgrassauer approved these changes

2018-07-24 12:46 UTC, y0chanan approved these changes

2018-07-24 13:10 UTC, merged