Overload for string deviceID
Dynatrace/openkit-dotnet pull request #54
Opened 2018-09-04 14:58 UTC by stefaneberl

This has the advantage that deviceIDs are no longer restricted
to be longs. It is possible to pass a 250 character long deviceID,
which can be a UUID or something similar.

2018-09-05 08:08 UTC, y0chanan approved these changes

2018-09-05 08:08 UTC, y0chanan commented on src/openkit-shared/Protocol/Beacon.cs
> +                DeviceID = randomNumberGenerator.NextLong(long.MaxValue).ToString(CultureInfo.InvariantCulture);
this is a line with a lot of stuff happening here. By introducing a linebreak the randomizer part and the string conversion can be split

2018-09-07 13:10 UTC, thomasgrassauer requested changes

2018-09-07 13:10 UTC, thomasgrassauer commented on src/openkit-shared/Protocol/Beacon.cs
> +        internal const int MAX_NAME_LEN = 250;
as you touched the const here. you might consider changing the name to comply with the C# naming conventions of constants. this also applies to other constants defined in Beacon.cs

2018-09-10 08:25 UTC, thomasgrassauer approved these changes

2018-09-10 08:54 UTC, merged